/**
 * KOYO Perfume Atelier - Data Repository (10ml Pure Perfume Oil Edition)
 * 17-accord database and scent descriptions.
 * OIL ONLY Workshop: No ethanol / alcohol. Pure fragrance oils measured in drops and grams.
 */

const ACCORDS_DATA = [
  // ==========================================
  // TOP NOTES (3)
  // ==========================================
  {
    id: "fresh-citrus",
    name: "Fresh Citrus Accord",
    family: "Fresh / Citrus",
    role: "TOP",
    roleLabel: "TOP NOTE",
    shortDescription: "Sparkling citrus brightness; clean first impression",
    fullDescription: "A dazzling burst of sun-drenched Italian bergamot, crisp lemon zest, and juicy mandarin. Lifts the fragrance with an immediate energetic radiance and luminous clarity.",
    volatility: "Fast Volatility (Opening Burst)",
    intensity: "Bright & Sparkling",
    recommendedPct: "15% – 25% (approx. 15–25 drops / 0.5–0.9g)",
    pairsWith: ["Pineapple Accord", "Black Currant Accord", "Hedione", "Iso E Super", "White Musk"],
    color: "#f59e0b",
    tags: ["Sparkling", "Bergamot", "Zesty", "Luminous"],
    perfumerTip: "Adds instant vitality and openness. Essential for an uplifting first impression on skin.",
    densityGramsPerDrop: 0.035
  },
  {
    id: "pineapple",
    name: "Pineapple Accord",
    family: "Fruity / Tropical",
    role: "TOP",
    roleLabel: "TOP NOTE",
    shortDescription: "Juicy tropical fruit; playful, bright and luminous",
    fullDescription: "Succulent, freshly sliced golden pineapple with tart exotic facets and a hint of caramelized natural sweetness. Brings modern vibrant optimism and juicy radiance.",
    volatility: "Fast Volatility (Tropical Lift)",
    intensity: "Bright & Tropical",
    recommendedPct: "15% – 25% (approx. 15–25 drops / 0.5–0.9g)",
    pairsWith: ["Black Currant Accord", "Fresh Citrus Accord", "Leather Accord", "Galaxolide", "Iso E Super"],
    color: "#eab308",
    tags: ["Juicy", "Tropical", "Playful", "Modern"],
    perfumerTip: "The iconic secret behind legendary modern luxury scents. Blends magnificently with Leather and Iso E Super.",
    densityGramsPerDrop: 0.036
  },
  {
    id: "black-currant",
    name: "Black Currant Accord",
    family: "Fruity / Berry",
    role: "TOP",
    roleLabel: "TOP NOTE",
    shortDescription: "Tart dark berry fruit; bold, modern punch",
    fullDescription: "Deep, purple-tinted cassis berries with crisp green leafy undertones and a tangy, mouthwatering contrast. Imparts an assertive, sophisticated fruit opening.",
    volatility: "Fast–Medium Volatility (Vibrant Punch)",
    intensity: "Rich & Tart",
    recommendedPct: "10% – 20% (approx. 10–20 drops / 0.35–0.7g)",
    pairsWith: ["Pineapple Accord", "Rose Honey Accord", "White Floral Accord", "Oud Accord", "White Musk"],
    color: "#a855f7",
    tags: ["Tart", "Bold", "Cassis", "Sophisticated"],
    perfumerTip: "Gives a bold contemporary edge. A few drops prevent sweet florals or rich vanillas from feeling flat.",
    densityGramsPerDrop: 0.035
  },

  // ==========================================
  // HEART NOTES (5)
  // ==========================================
  {
    id: "lotus",
    name: "Lotus Accord",
    family: "Floral / Aquatic",
    role: "HEART",
    roleLabel: "HEART NOTE",
    shortDescription: "Watery soft floral; airy, elegant and delicate",
    fullDescription: "Dewy lotus blossoms floating over clear morning spring water. Translucent, calming, poetic, and pristine with gentle green petal nuances and serene aquatic softness.",
    volatility: "Medium Volatility (Airy Floral Body)",
    intensity: "Delicate & Airy",
    recommendedPct: "12% – 22% (approx. 12–22 drops / 0.4–0.8g)",
    pairsWith: ["White Floral Accord", "Fresh Citrus Accord", "Hedione", "White Musk", "Galaxolide"],
    color: "#06b6d4",
    tags: ["Watery", "Airy", "Serene", "Delicate"],
    perfumerTip: "Creates a dreamy, modern aquatic-floral breeze. Opens up dense heavy formulas.",
    densityGramsPerDrop: 0.035
  },
  {
    id: "white-floral",
    name: "White Floral Accord",
    family: "Floral",
    role: "HEART",
    roleLabel: "HEART NOTE",
    shortDescription: "Creamy floral body; polished and opulent",
    fullDescription: "A lush, velvety bouquet of gardenia, night-blooming jasmine, and white tuberose petals. Silky, opulent, captivating, and timelessly elegant fine fragrance heart.",
    volatility: "Medium–Long Tenacity (Opulent Body)",
    intensity: "Opulent & Polished",
    recommendedPct: "15% – 25% (approx. 15–25 drops / 0.5–0.9g)",
    pairsWith: ["Rose Honey Accord", "Lotus Accord", "Hedione", "Marshmallow Accord", "Vanilla Accord"],
    color: "#ec4899",
    tags: ["Creamy", "Opulent", "Jasmine", "Velvety"],
    perfumerTip: "The heart and soul of classic fine perfumery. Imparts magnificent sillage and creamy luxury body.",
    densityGramsPerDrop: 0.036
  },
  {
    id: "rose-honey",
    name: "Rose Honey Accord",
    family: "Floral / Sweet",
    role: "HEART",
    roleLabel: "HEART NOTE",
    shortDescription: "Velvety Damask rose with golden acacia honeyed warmth",
    fullDescription: "Rich Damask rose petals drizzled with golden artisanal acacia honey and warm morning floral nectar. Deeply romantic, sensual, warm, and invitingly cozy.",
    volatility: "Medium–Long Tenacity (Sensual Core)",
    intensity: "Sensual & Honeyed",
    recommendedPct: "10% – 20% (approx. 10–20 drops / 0.35–0.7g)",
    pairsWith: ["White Floral Accord", "Vanilla Accord", "Tobacco Accord", "Oud Accord", "Marshmallow Accord"],
    color: "#f43f5e",
    tags: ["Romantic", "Honeyed", "Warm", "Sensual"],
    perfumerTip: "Pairs divinely with Tobacco and Oud to create irresistible Eastern-niche warmth and magnetic intimacy.",
    densityGramsPerDrop: 0.037
  },
  {
    id: "hedione",
    name: "Hedione",
    family: "Transparent Floral / Booster",
    role: "HEART",
    roleLabel: "HEART NOTE",
    shortDescription: "Luminous transparent jasmine booster & diffusion enhancer",
    fullDescription: "The legendary aroma chemical that revolutionized luxury perfumery (Eau Sauvage). Imparts radiant floral airiness, dew-like morning transparency, and expands all surrounding notes effortlessly.",
    volatility: "Medium–Long Tenacity (Radiant Diffuser)",
    intensity: "Transparent & Diffusive",
    recommendedPct: "10% – 20% (approx. 10–20 drops / 0.35–0.7g)",
    pairsWith: ["Fresh Citrus Accord", "Iso E Super", "White Floral Accord", "Lotus Accord", "Galaxolide"],
    color: "#38bdf8",
    tags: ["Radiant", "Booster", "Transparent", "Diffusion"],
    perfumerTip: "The master perfumer's secret weapon. It breathes air and radiance into heavy oils, giving roll-on oil incredible projection.",
    densityGramsPerDrop: 0.035
  },
  {
    id: "marshmallow",
    name: "Marshmallow Accord",
    family: "Sweet / Confectionery",
    role: "HEART",
    roleLabel: "HEART NOTE",
    shortDescription: "Powdery fluffy sweetness; soft, playful and nostalgic",
    fullDescription: "Airy spun sugar confection dusted with delicate powdered vanilla and soft white blossom sugar. Fluffy, nostalgic, sweet, and comforting cloud-like heart texture.",
    volatility: "Medium–Long Tenacity (Velvet Cloud)",
    intensity: "Soft & Powdery",
    recommendedPct: "8% – 18% (approx. 8–18 drops / 0.3–0.6g)",
    pairsWith: ["White Floral Accord", "Rose Honey Accord", "Gourmand Accord", "Vanilla Accord", "White Musk"],
    color: "#f472b6",
    tags: ["Fluffy", "Powdery", "Playful", "Sweet"],
    perfumerTip: "Smoothens sharp edges in citrus or spicy accords, giving the blend a soft comforting aura.",
    densityGramsPerDrop: 0.035
  },

  // ==========================================
  // BASE NOTES (9)
  // ==========================================
  {
    id: "gourmand",
    name: "Gourmand Accord",
    family: "Sweet / Warm",
    role: "BASE",
    roleLabel: "BASE NOTE",
    shortDescription: "Warm caramelized sugar, roasted praline and hazelnut cream",
    fullDescription: "Decadent caramelized sugar, roasted praline, velvety vanilla bean, and toasted hazelnut cream. Irresistibly comforting, indulgent, and addictive evening anchor.",
    volatility: "Long Tenacity (Deep Warmth)",
    intensity: "Warm & Round",
    recommendedPct: "8% – 18% (approx. 8–18 drops / 0.3–0.6g)",
    pairsWith: ["Marshmallow Accord", "Vanilla Accord", "Tobacco Accord", "Oud Accord", "White Musk"],
    color: "#d97706",
    tags: ["Cozy", "Edible", "Praline", "Indulgent"],
    perfumerTip: "Use with a measured hand for a sophisticated cozy halo, or increase for a decadent edible signature.",
    densityGramsPerDrop: 0.036
  },
  {
    id: "vanilla",
    name: "Vanilla Accord",
    family: "Warm Sweet / Gourmand",
    role: "BASE",
    roleLabel: "BASE NOTE",
    shortDescription: "Creamy bourbon vanilla bean, rich comforting anchor",
    fullDescription: "Pure Madagascar bourbon vanilla bean infused with creamy amber and smooth woody undertones. Universal, sensual, comforting, and deeply addictive drydown warmth.",
    volatility: "Long Tenacity (Sensual Anchor)",
    intensity: "Rich & Comforting",
    recommendedPct: "10% – 20% (approx. 10–20 drops / 0.35–0.7g)",
    pairsWith: ["Tobacco Accord", "Oud Accord", "Rose Honey Accord", "Gourmand Accord", "Iso E Super"],
    color: "#b45309",
    tags: ["Bourbon", "Creamy", "Sensual", "Addictive"],
    perfumerTip: "Unifies woody and floral accords into a smooth, seamless texture. Balances dark smoke and leather effortlessly.",
    densityGramsPerDrop: 0.036
  },
  {
    id: "iso-e-super",
    name: "Iso E Super",
    family: "Woody / Ambergris",
    role: "BASE",
    roleLabel: "BASE NOTE",
    shortDescription: "Velvety cedarwood & ambergris aura; modern pheromone radiance",
    fullDescription: "The iconic molecule behind Molecule 01. A smooth, expanding cedarwood-ambergris aura that feels transparent, magnetic, and second-skin. Blends into human body warmth.",
    volatility: "Ultra-Long Tenacity (Expanding Halo)",
    intensity: "Subtle & Magnetic",
    recommendedPct: "15% – 30% (approx. 15–30 drops / 0.5–1.0g)",
    pairsWith: ["Hedione", "Oud Accord", "Pineapple Accord", "White Musk", "Galaxolide"],
    color: "#64748b",
    tags: ["Velvety", "Cedarwood", "Molecule", "Pheromonic"],
    perfumerTip: "Creates that elusive, compliment-pulling aura. People smell it around you even when you think it has faded.",
    densityGramsPerDrop: 0.035
  },
  {
    id: "white-musk",
    name: "White Musk",
    family: "Clean Musk",
    role: "BASE",
    roleLabel: "BASE NOTE",
    shortDescription: "Clean skin-like softness; smooth, intimate and wearable",
    fullDescription: "Pristine sun-dried white linen, freshly laundered cotton, and warm intimate skin. The ultimate clean, universally flattering everyday signature anchor.",
    volatility: "Long Tenacity (Second-Skin Sillage)",
    intensity: "Intimate & Clean",
    recommendedPct: "15% – 25% (approx. 15–25 drops / 0.5–0.9g)",
    pairsWith: ["Galaxolide", "Ethylene Brassylate", "Lotus Accord", "Iso E Super", "Vanilla Accord"],
    color: "#94a3b8",
    tags: ["Clean", "Skin-Scent", "Smooth", "Modern"],
    perfumerTip: "Acts as the foundation for your fragrance oil. Melts accords together and prevents clashing notes.",
    densityGramsPerDrop: 0.035
  },
  {
    id: "galaxolide",
    name: "Galaxolide",
    family: "Clean Floral Musk",
    role: "BASE",
    roleLabel: "BASE NOTE",
    shortDescription: "Diffusive clean musk; adds room-filling softness and volume",
    fullDescription: "A renowned master-perfumer musk that imparts remarkable radiant projection, sweet-floral floralcy, and a soft velvety aura that extends oil presence.",
    volatility: "Ultra-Long Tenacity (Diffusive Volume)",
    intensity: "Radiant & Diffusive",
    recommendedPct: "10% – 20% (approx. 10–20 drops / 0.35–0.7g)",
    pairsWith: ["White Musk", "Ethylene Brassylate", "Pineapple Accord", "White Floral Accord", "Hedione"],
    color: "#818cf8",
    tags: ["Radiant", "Diffusive", "Volume", "Velvety"],
    perfumerTip: "Adds immense sillage and space between notes. Essential for making your perfume oil project effortlessly.",
    densityGramsPerDrop: 0.036
  },
  {
    id: "ethylene-brassylate",
    name: "Ethylene Brassylate",
    family: "Sweet Macrocyclic Musk",
    role: "BASE",
    roleLabel: "BASE NOTE",
    shortDescription: "Smooth elegant musk; master fixative that extends drydown",
    fullDescription: "A sophisticated macrocyclic musk with subtle sweet-woody and soft ambrette undertones. Provides unmatched fixative power and lasting skin persistence in oil blends.",
    volatility: "Ultra-Long Tenacity (Master Fixative)",
    intensity: "Smooth Fixative",
    recommendedPct: "10% – 20% (approx. 10–20 drops / 0.35–0.7g)",
    pairsWith: ["White Musk", "Galaxolide", "Leather Accord", "Tobacco Accord", "Oud Accord"],
    color: "#6366f1",
    tags: ["Fixative", "Elegant", "Longevity", "Tenacious"],
    perfumerTip: "The ultimate natural-feeling fixative. Anchors top notes so they don't disappear after the opening.",
    densityGramsPerDrop: 0.036
  },
  {
    id: "leather",
    name: "Leather Accord",
    family: "Dark / Leather",
    role: "BASE",
    roleLabel: "BASE NOTE",
    shortDescription: "Dry, textured suede depth; bold and sophisticated",
    fullDescription: "Supple tanned saddle leather, birch tar smoke, and refined suede warmth. Imparts unmistakable confidence, luxury, and daring depth to pure oil blends.",
    volatility: "Long Tenacity (Smoky Texture)",
    intensity: "Bold & Textured",
    recommendedPct: "3% – 8% (approx. 3–8 drops / 0.1–0.3g)",
    pairsWith: ["Pineapple Accord", "Fresh Citrus Accord", "Tobacco Accord", "Oud Accord", "Iso E Super"],
    color: "#78350f",
    tags: ["Textured", "Bold", "Smoky", "Haute"],
    perfumerTip: "Highly potent! 3–6 drops add masculine confidence and niche depth without dominating the formula.",
    densityGramsPerDrop: 0.037
  },
  {
    id: "tobacco",
    name: "Tobacco Accord",
    family: "Warm / Smoky",
    role: "BASE",
    roleLabel: "BASE NOTE",
    shortDescription: "Warm smoky sweet blonde tobacco leaves; rich and sensual",
    fullDescription: "Sun-cured golden Virginia tobacco leaf laced with roasted honey, dry tonka bean, and sweet amber smoke. Intoxicating, opulent, and magnetic evening warmth.",
    volatility: "Long Tenacity (Sensual Sillage)",
    intensity: "Rich & Sensual",
    recommendedPct: "5% – 12% (approx. 5–12 drops / 0.2–0.45g)",
    pairsWith: ["Vanilla Accord", "Rose Honey Accord", "Oud Accord", "Gourmand Accord", "Leather Accord"],
    color: "#92400e",
    tags: ["Smoky", "Opulent", "Sensual", "Warm"],
    perfumerTip: "Brings mysterious evening warmth and magnetic intimacy when combined with vanilla or rose honey.",
    densityGramsPerDrop: 0.036
  },
  {
    id: "oud",
    name: "Oud Accord",
    family: "Woody / Oriental",
    role: "BASE",
    roleLabel: "BASE NOTE",
    shortDescription: "Deep resinous oriental agarwood; dark luxury backbone",
    fullDescription: "Regal agarwood resin enriched with smoky balsamic woods, warm saffron undertones, and velvet amber. The pinnacle of Eastern haute parfumerie prestige.",
    volatility: "Ultra-Long Tenacity (Regal Sillage)",
    intensity: "Deep & Majestic",
    recommendedPct: "4% – 12% (approx. 4–12 drops / 0.15–0.45g)",
    pairsWith: ["Rose Honey Accord", "Vanilla Accord", "Tobacco Accord", "Iso E Super", "Black Currant Accord"],
    color: "#451a03",
    tags: ["Agarwood", "Majestic", "Resinous", "Prestige"],
    perfumerTip: "A few drops give any perfume oil an instantly expensive, regal niche aura. Blends majestically with Rose Honey and Vanilla.",
    densityGramsPerDrop: 0.037
  }
];


// Hidden search vocabulary: scent associations, moods, seasons and common names.
const SCENT_SEARCH_TAGS = {
  'fresh-citrus': 'sour tart tangy sharp acidic zest zesty lemon lime orange mandarin bergamot grapefruit citrus fresh refreshing cool cooling crisp clean bright sunny sunshine summer summery spring daytime morning energetic uplifting sparkling light juicy beach vacation holiday sporty unisex lemonade nimbu khatta',
  pineapple: 'sour tart tangy sweet juicy fruity fruit tropical exotic yellow sunny sunshine summer summery beach vacation holiday playful cheerful fun bright fresh cocktail island ananas sweet-sour',
  'black-currant': 'sour tart tangy sharp fruity fruit berry berries dark purple cassis blackcurrant currant green leafy juicy bold modern summer spring autumn fall jam punch sophisticated fruity-sour',
  lotus: 'cool cooling fresh refreshing watery aquatic water rain rainy dewy dew breezy airy light delicate soft floral flower flowers clean serene calm calming peaceful spa zen relaxing spring summer summery morning daytime ocean sea beach green petals transparent',
  'white-floral': 'floral flower flowers bouquet jasmine gardenia tuberose white creamy lush rich soft silky elegant classic polished romantic romance wedding bridal feminine spring summer evening garden blooming blossom blossoms',
  'rose-honey': 'rose rosy floral flower flowers petals honey nectar sweet warm warmth cozy cosy romantic romance date night evening wedding bridal autumn fall winter sensual rich velvety soft golden gulab shehad',
  hedione: 'jasmine floral flower flowers airy air light transparent fresh refreshing cool clean bright luminous radiant breezy dewy soft subtle spring summer summery daytime morning diffusion booster lift spacious modern unisex',
  marshmallow: 'sweet sugar sugary candy confection dessert vanilla powder powdery fluffy soft cozy cosy comforting comfort playful nostalgic pastel pink feminine romantic winter autumn fall cotton candy cloud',
  gourmand: 'sweet sugar sugary dessert edible caramel praline hazelnut nutty nuts roasted toasted creamy rich warm warmth cozy cosy comforting comfort indulgent bakery cake candy chocolate gourmand autumn fall winter evening date night',
  vanilla: 'sweet vanilla creamy cream milky smooth soft warm warmth cozy cosy comforting comfort dessert bakery cake cookies cookie ice cream bourbon amber rich sensual romantic winter autumn fall evening date night',
  'iso-e-super': 'wood woods woody cedar cedarwood amber ambergris smooth velvety dry transparent airy subtle minimalist minimal modern molecule skin second skin intimate clean soft unisex masculine office everyday daytime autumn fall',
  'white-musk': 'musk musky clean fresh refreshing cool soft smooth skin intimate subtle minimalist minimal everyday office daytime linen laundry cotton soap soapy shower powder powdery cozy cosy comforting comfort spring summer summery unisex',
  galaxolide: 'musk musky clean laundry linen cotton soap soapy soft fluffy smooth sweet floral airy radiant diffusive diffusion volume powder powdery fresh everyday office spring summer unisex',
  'ethylene-brassylate': 'musk musky soft smooth sweet subtle elegant warm skin intimate woody ambrette clean powder powdery round rounding gentle comforting cozy cosy drydown fixative lasting longevity base everyday unisex winter',
  leather: 'leather leathery suede dry textured smoky smokey smoke birch saddle dark bold daring deep depth rich warm rugged masculine sophisticated niche autumn fall winter evening night jacket',
  tobacco: 'tobacco smoky smokey smoke warm warmth sweet dark deep rich cozy cosy dry aromatic golden honey leaves leaf autumn fall winter evening night masculine sophisticated lounge',
  oud: 'oud oudh wood woods woody agarwood resin resinous dark deep depth rich warm warmth smoky smokey smoke earthy bold intense oriental eastern arabic arabian attar luxury incense bakhoor autumn fall winter evening night unisex masculine'
};
for (const note of ACCORDS_DATA) note.searchTags = SCENT_SEARCH_TAGS[note.id].split(' ');
